### PR TITLE
Changed the projects headers to show hierarchy

### PR DESCRIPTION
**Pull request by MM422**
As discussed with @joyeecheung in her commit([#13](https://github.com/nodejs/automation/pull/13)) before to change the header so that it could should better hierarchy

### CODE REVIEW

**Review by Tiriel — APPROVED** [review]
LGTM

**Comment by MM422** [comment]
I found I don't have access to merge it. @joyeecheung May I ask, could you merge it? :)

**Review by joyeecheung — APPROVED** [review]

**Comment by joyeecheung** [comment]
I've changed the commit message a bit and merged it. Thanks!

**Comment by MM422** [comment]
@joyeecheung Sorry about that. I have changed the corresponding message. 😃

**Pull request merged**
